
name: CI-CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: zayn63/strapi-task10
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_test_push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          cd app
          npm install

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $DOCKER_IMAGE:$IMAGE_TAG ./app

      # 5. Run minimal test (smoke test)
      - name: Run smoke test
        run: |
          echo "Simulating test: container build successful"

      # 6. Log in to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Push Docker image
      - name: Push Docker image
        run: |
          docker push $DOCKER_IMAGE:$IMAGE_TAG

      # 8. Simulate ECS deploy
      - name: Simulate ECS deploy
        run: |
          echo "Simulating ECS deployment..."
          echo "ECS task definition would use image: $DOCKER_IMAGE:$IMAGE_TAG"
